NET.addAssembly('D:\Code\SystemControl\GSI\bin\Debug\GSI.dll')
gsiasm=NET.addAssembly('D:\Code\SystemControl\GSI\bin\Debug\GSI.dll')
%-- 28/09/2014 12:24 --%
gsiasm=NET.addAssembly('D:\Code\SystemControl\GSI\bin\Debug\GSI.dll')
reader=GSI.Storage.Spectrum.SpectrumStreamReader.Open('smaple_med.rawstack.forier.sdat');
reader=GSI.Storage.Spectrum.SpectrumStreamReader.Open('D:\Measurments\20140918\smaple_med.rawstack.forier.sdat');
reader
reader.Settings.Height
reader.Settings.Width
reader.ReadSpectrumPixel(4322,1000)
arr=reader.ReadSpectrumPixel(4322,1000)
arr
arr(:)=arr(:)
arr(:)=cell2mat(arr)
arr
cell(arr)
arr.uint16
arr.uint32
arr.uint64
arr
arr.double
arr.single
arr
arr.double
clear
clc
reader=GSI.Storage.Spectrum.SpectrumStreamReader.Open('D:\Measurments\20140918\smaple_med.rawstack.forier.sdat');
%-- 28/09/2014 12:41 --%
reader=GSI.Storage.Spectrum.SpectrumStreamReader.Open('D:\Measurments\20140918\smaple_med.rawstack.forier.sdat');
NET.addAssembly('D:\Code\SystemControl\GSI\bin\Debug\GSI.dll')
reader=GSI.Storage.Spectrum.SpectrumStreamReader.Open('D:\Measurments\20140918\smaple_med.rawstack.forier.sdat');
reader.Close()
reader=[]
reader=GSI.Storage.Spectrum.SpectrumStreamReader.Open('D:\Measurments\20140918\smaple_med.rawstack.forier.sdat');
reader
reader.Settings.NumberOfPrecisionBytes
reader.Settings.NumberOfPixels
reader.ReadSpectrumPixel(22,34)
reader.ReadSpectrumPixel(22,34).single
plot(reader.ReadSpectrumPixel(22,34).single)
reader.Close()
plot(reader.ReadSpectrumPixel(22,34).single)
GSI.IP.SpectrumPreviewGenerator.Create
reader=GSI.Storage.Spectrum.SpectrumStreamReader.Open('D:\Measurments\20140918\smaple_med.rawstack.forier.sdat');
w=reader.Settings.Width
h=reader.Settings.Height
reader.Close()
fn='D:\Measurments\20140918\smaple_med.rawstack.forier.sdat';
generator=GSI.IP.SpectrumPreviewGenerator.Create(fn,[fn,'.prevval.blat'],w,h);
%-- 28/09/2014 12:50 --%
reader=GSI.Storage.Spectrum.SpectrumStreamReader.Open('D:\Measurments\20140918\smaple_med.rawstack.forier.sdat');
NET.addAssembly('D:\Code\SystemControl\GSI\bin\Debug\GSI.dll')
reader=GSI.Storage.Spectrum.SpectrumStreamReader.Open('D:\Measurments\20140918\smaple_med.rawstack.forier.sdat');
w=reader.Settings.Width
h=reader.Settings.Height
reader.Close()
generator=GSI.IP.SpectrumPreviewGenerator.Create(fn,[fn,'.prevval.blat'],w,h);
fn='D:\Measurments\20140918\smaple_med.rawstack.forier.sdat';
generator=GSI.IP.SpectrumPreviewGenerator.Create(fn,[fn,'.prevval.blat'],w,h);
generator
gen=generator
gen.Make()
gen
gen.Make(true,false)
gen=GSI.IP.SpectrumPreviewGenerator.Create(fn,[fn,'.prevval.blat'],w,h);
generator.Close()
gen=GSI.IP.SpectrumPreviewGenerator.Create(fn,[fn,'.prevval.blat'],w,h);
gen.Make(true,false)
gen.Close()
gen=GSI.IP.SpectrumPreviewGenerator.Create(fn,[fn,'.prevval.blat'],w,h);
%-- 28/09/2014 12:57 --%
fn='D:\Measurments\20140918\smaple_med.rawstack.forier.sdat';
reader=GSI.Storage.Spectrum.SpectrumStreamReader.Open(fn);
NET.addAssembly('D:\Code\SystemControl\GSI\bin\Debug\GSI.dll')
reader=GSI.Storage.Spectrum.SpectrumStreamReader.Open(fn);
w=reader.Settings.Width
h=reader.Settings.Height
reader.Close()
gen=GSI.IP.SpectrumPreviewGenerator.Create(fn,[fn,'.prevval.blat'],w,h);
ls
gen
gen.Close()
gen=GSI.IP.SpectrumPreviewGenerator.Create(fn,[fn,'.prevval.blat'],w,h);
gen.Close()
TestrunC#
TestrunC
gen.Processor.IsRunning
TestrunC
gen.Close()
TestrunC
gen.Close()
clear
%-- 28/09/2014 13:05 --%
NET.addAssembly('D:\Code\SystemControl\GSI\bin\Debug\GSI.dll')
GSI.IP
fn='D:\Measurments\20140918\smaple_med.rawstack.forier.sdat';
GSI.IP.PreviewStream.Open([fn,
prev=GSI.IP.PreviewStream.Open([fn,'.prevval.blat']);
prev=GSI.IP.PreviewStream.Open([fn,'.prevdat']);
%-- 28/09/2014 13:08 --%
NET.addAssembly('D:\Code\SystemControl\GSI\bin\Debug\GSI.dll')
prev=GSI.IP.PreviewStream.Open([fn,'.prevdat']);
fn='D:\Measurments\20140918\smaple_med.rawstack.forier.sdat';
prev=GSI.IP.PreviewStream.Open([fn,'.prevdat']);
prev.Close()
%-- 28/09/2014 13:16 --%
fn='D:\Measurments\20140918\smaple_med.rawstack.forier.sdat';
NET.addAssembly('D:\Code\SystemControl\GSI\bin\Debug\GSI.dll')
prev=GSI.IP.PreviewStream.Open([fn,'.prevdat']);
%-- 28/09/2014 13:18 --%
NET.addAssembly('D:\Code\SystemControl\GSI\bin\Debug\GSI.dll')
fn='D:\Measurments\20140918\smaple_med.rawstack.forier.sdat';
prev=GSI.IP.PreviewStream.Open([fn,'.prevdat']);
prev.GetDrawBits(0,0,100,100)
prevd=prev.GetDrawBits(0,0,100,100)
prevd.int8
prev.Close()