//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSIGateway.ExampleRefrence {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ExampleRefrence.ExampleControllerSoap")]
    public interface ExampleControllerSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Goto", ReplyAction="*")]
        bool Goto(double x, double y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Goto", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> GotoAsync(double x, double y);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ExampleControllerSoapChannel : GSIGateway.ExampleRefrence.ExampleControllerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExampleControllerSoapClient : System.ServiceModel.ClientBase<GSIGateway.ExampleRefrence.ExampleControllerSoap>, GSIGateway.ExampleRefrence.ExampleControllerSoap {
        
        public ExampleControllerSoapClient() {
        }
        
        public ExampleControllerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExampleControllerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExampleControllerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExampleControllerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Goto(double x, double y) {
            return base.Channel.Goto(x, y);
        }
        
        public System.Threading.Tasks.Task<bool> GotoAsync(double x, double y) {
            return base.Channel.GotoAsync(x, y);
        }
    }
}
